services:
  - type: web
    name: fridgeai
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
